workflows:
  ios-workflow:
    name: iOS Codemagic Build
    max_build_duration: 60
    environment:
      flutter: 3.32.5
      xcode: latest
    scripts:
      - name: Clean and generate iOS framework
        script: |
          flutter clean
          flutter pub get
          flutter build ios-framework --output=ios/Flutter/ --no-profile --no-debug --cocoapods
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
      - flutter_drive.log
