workflows:
  ios-workflow:
    name: iOS Codemagic Build
    max_build_duration: 60
    environment:
      flutter: 3.32.5
      xcode: latest
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
          rm -rf ios/Pods ios/Flutter ios/.symlinks ios/Podfile.lock
          cd ios
          pod install
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
      - flutter_drive.log
