platform :ios, '15.5'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(application_path: File.dirname(File.realpath(__FILE__)))

  pod 'Firebase/Core', '10.20.0'
  pod 'FirebaseAnalytics', '10.20.0'
  pod 'FirebaseCoreInternal', '10.20.0'
end
